name: workshop

services:
  postgres:
    image: postgres:16-alpine@sha256:721873c34ceb9f8d8fc265984940dc982404c105f19ad51be9fdc5970a6080ea
    environment:
      POSTGRES_USER: pact
      POSTGRES_PASSWORD: pact
      POSTGRES_DB: pact
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pact"]
      interval: 2s
      retries: 30

  broker:
    image: pactfoundation/pact-broker@sha256:420341d4fbfb00a621c313f47e530ad75703f969bbc7520d0d72bc71bb53cef9
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "9292:9292"
    environment:
      PACT_BROKER_DATABASE_URL: postgres://pact:pact@postgres/pact
      PACT_BROKER_LOG_LEVEL: WARN

  user-service:
    image: user-service:${USER_SERVICE_VERSION}
    pull_policy: never

  order-service:
    image: order-service:${ORDER_SERVICE_VERSION}
    pull_policy: never
    environment:
      USER_SERVICE_URL: http://user-service:5000
    ports:
      - "8080:5000"

networks:
  default:
    name: workshop